### PR TITLE
added accessibility id as a locator

### PR DESCRIPTION
**Pull request by rvenky125**
# Overview
Thank you very much for merging the previous PR, and I would kindly request that you please merge this one as we need the accessibility locator also, and it's useful for many of the users.

# Test Plan
You can just check if the locator is reflecting as accessibility-id in Appium Inspector.

### CODE REVIEW

**Review by Naturalclar — CHANGES_REQUESTED** [review]
@rvenky125 thanks for the changes! could you address the lint error?

**Comment by rvenky125** [comment]
Yes, will update the pr asap

**Comment by rvenky125** [comment]
Hey @Naturalclar, I addressed those checks, Thank you.

**Review by Naturalclar — APPROVED** [review]
LGTM

**Comment by rvenky125** [comment]
Thanks for merging; I'm eagerly waiting for a new release

**Comment by Naturalclar** [comment]
@rvenky125 thanks for the ping! released v2.5.6 with changes included

**Pull request merged**
